# Generated by Django 6.0.3 on 2026-03-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
